version: '3'

services:
  postgresql:
    image: postgres:latest
    env_file:
      - .env
    networks:
      - network
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ../PROJECT-The-sewing-company/backend
    env_file:
      - .env
    networks:
      - network
    volumes:
      - static:/code/static
      - "./backend:/code"

    ports:
      - "9000:9000"
    depends_on:
      - postgresql

networks:
  network:

volumes:
  db_data:
  static: